app:
  port: 8000
database:
  name: newsletter
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: password
email_client:
  base_url: localhost
  sender_email: test@gmail.com
  timeout_ms: 10000
